version: '3.8'

services:
  # Redis service for Django Channels
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

  # Backend service
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,backend,frontend,127.0.0.1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=sqlite:///db.sqlite3
      - CORS_ALLOWED_ORIGINS=http://frontend:5173,http://localhost:5173,http://localhost:3000
    restart: unless-stopped
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge